### ISSUE TITLE
Phase 2: Contract Initiation

### ISSUE THREAD

**Issue by kagreen70** [krusynth/digitalpolicy#15]
Current:
As part of any contract, the government must come up with an initial estimate. For labor contracts, it can be useful to refer to the General Services Administration’s published rates ([GSA Pricing Tool](https://buy.gsa.gov/pricing/)).

Suggested Change:
As part of any contract, the government must come up with an initial **cost** estimate**, which is called the Independent Government Cost Estimate (IGCE).** For labor contracts, it can be useful to refer to the General Services Administration’s published rates ([GSA Pricing Tool](https://buy.gsa.gov/pricing/)).

**Comment by krusynth** [comment]
Thanks for catching these!  I really appreciate it!
