### ISSUE TITLE
OpenGraph descriptions are incomplete

### ISSUE THREAD

**Issue by NGTmeaty** [krusynth/digitalpolicy#21]
For example: https://digitalpolicy.us/laws/antideficiency-act/

`<meta property="og:description" content="The Antideficiency Act is the one of the fundamental laws for the Federal budget and contracting. @GAO notes that the law prohibits federal employees from:" />`

With `@GAO` sticking out.

Possibly a bug in [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag)? We could manually set the description on these pages and make them more complete.

Not a huge issue but I wanted to flag it.

**Comment by krusynth** [comment]
Yeah, this is a jekyll-seo-tag thing, but moreover laziness on my part in failing to create explicit summaries on every page.  That's a pretty big undertaking but I'll start poking at this!
