### ISSUE TITLE
The Computer Chaos (Cohen Report) is inaccessible at linked URL

### ISSUE THREAD

**Issue by NGTmeaty** [krusynth/digitalpolicy#22]
I see https://digitalpolicy.us/uploads/Cohen%20Computer%20Chaos%201994.pdf is returning this instead of the PDF:

```
version https://git-lfs.github.com/spec/v1
oid sha256:cc2f29263b14294f9feffd8561c8e713a2c67a6c3ce8d6536099ddecfb36f78b
size 3276459
```

It seems like Git LFS doesn't work in conjunction with GitHub pages? (see ref: https://github.com/git-lfs/git-lfs/issues/1342 https://github.com/git-lfs/git-lfs/issues/3498 )

We could use this "solution" https://github.com/git-lfs/git-lfs/issues/1342#issuecomment-467321479 to "fix" it. With "https://media.githubusercontent.com/media/krusynth/digitalpolicy/ghpages/uploads/Cohen%20Computer%20Chaos%201994.pdf" returning the PDF. But I'm not sure what the best solution here is. Maybe hosting it somewhere else or just putting it in the repo (it's not that big!).

**Comment by krusynth** [comment]
Thanks!  I've updated this with your suggested fix.

Regarding git lfs, on my other projects I will sometimes stash large files like this in the github wiki repo instead, but since there's only one here I'm not too worried at the moment.  Something to revisit if it becomes an issue.
