### ISSUE TITLE
Add section on social media use while working in the federal government 

### ISSUE THREAD

**Issue by daguar** [krusynth/digitalpolicy#25]
Hi Bill! Really enjoying the site.

It dawns on me an area you may have developed some experience in by practice is guardrails on social media use while working in the federal government. I think this might be useful additional content, given that folks entering from tech sector  roles may have different implicit expectations.

Thanks!

**Comment by krusynth** [comment]
Ah yes! I probably should add a whole section on ethics. Off the top of my head:

* [x] Conflict of Interest (Procurement)
* [x] Form 450 (financial disclosure / hiring)
* [x] Public Speaking / Use of Social Media
* [x] Equal access / preferential treatment of vendors (Procurement)

**Comment by daguar** [comment]
🙏 :shipit:
