### ISSUE TITLE
Accessibility contrast issues

### ISSUE THREAD

**Issue by lukefretwell** [krusynth/digitalpolicy#3]
Great work @krusynth!

Note there are a significant number contrast issues with the site:

https://wave.webaim.org/report#/https://digitalpolicy.us/

**Comment by bengm** [comment]
Funny. We did this in parallel, but it looks like you beat me to it!

https://github.com/krusynth/digitalpolicy/issues/5

**Comment by krusynth** [comment]
Thanks Ben & Luke!  I just went ahead and used the [USWDS](https://github.com/uswds/uswds) colors!
